---

# Use `defaults read` to dump out the current settings.

- name: disable sound on boot
  sudo: yes
  command: nvram SystemAudioVolume=" "

- name: enable tap-to-click
  sudo: yes
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

- name: enable display zooming
  sudo: yes
  command: defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

- name: set ctrl+shift+scroll to zoom
  sudo: yes
  command: defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 393216

- name: show all filename extensions
  sudo: yes
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: show the ~/Library folder
  sudo: yes
  command: chflags nohidden ~/Library

- name: don’t automatically rearrange Spaces based on most recent use
  sudo: yes
  command: defaults write com.apple.dock mru-spaces -bool false

- name: automatically hide and show the Dock
  sudo: yes
  command: defaults write com.apple.dock autohide -bool true

- name: set the default dock size to fairly large
  sudo: yes
  command: defaults write com.apple.dock largesize -int 90

- name: speed up window resize animations
  sudo: yes
  command: defaults write -g NSWindowResizeTime -float 0.001

- name: significantly speed up expose (skip animation)
  sudo: yes
  command: defaults write com.apple.dock expose-animation-duration -int 0
  notify:
    - restart the dock

# TODO:
# - name: dvorak keyboard layout
# - name: replace capslock with left ctrl
# - name: cmd-[0-9] switches spaces
